export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR =
  "REMOVE_INGREDIENT_FROM_CONSTRUCTOR";

export const REORDER_INGREDIENT = "REORDER_INGREDIENT";

export const ADD_INGREDIENT_TO_CONSTRUCTOR = "ADD_INGREDIENT_TO_CONSTRUCTOR";
