export const EMAIL_PASSWORD_RESET_LINK = "EMAIL_PASSWORD_RESET_LINK";
export const EMAIL_PASSWORD_RESET_LINK_SUCCESS =
  "EMAIL_PASSWORD_RESET_LINK_SUCCESS";
export const EMAIL_PASSWORD_RESET_LINK_FAIL = "EMAIL_PASSWORD_RESET_LINK_FAIL";
