export const SAVE_CURRENT_INGREDIENT_DETAILS =
  "SAVE_CURRENT_INGREDIENT_DETAILS";
export const REMOVE_CURRENT_INGREDIENT_DETAILS =
  "REMOVE_CURRENT_INGREDIENT_DETAILS";
export const GET_INGREDIENT_DETAILS = "GET_INGREDIENT_DETAILS";
export const GET_INGREDIENT_DETAILS_SUCCESS = "GET_INGREDIENT_DETAILS_SUCCESS";
export const GET_INGREDIENT_DETAILS_FAIL = "GET_INGREDIENT_DETAILS_FAIL";
