export const GET_ORDER_DESCRIPTION = "GET_ORDER_DESCRIPTION";
export const GET_ORDER_DESCRIPTION_SUCCESS = "GET_ORDER_DESCRIPTION_SUCCESS";
export const GET_ORDER_DESCRIPTION_FAIL = "GET_ORDER_DESCRIPTION_FAIL";
